### ISSUE TITLE
Make ajax handle varying capitalizations on `type`

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-util#100]
Currently:

```
can.ajax({
      type: "post",
      url: "/verifyCard",
      data: this.serialize()
    })
```

Doesn't post because it needs to be `"POST"`.  

Related: https://github.com/canjs/can-util/issues/90

**Comment by prashantsharmain** [comment]
@justinbmeyer @iherdon 

I have a fix for this, but having trouble writing a unit test. 

http-server by default doesn't support POST requests, and the unit test fails with a 405 Method Not Allowed response. I could use a different http server to run the tests locally, but I'm unsure if the build would pass on Travis. 

If you have any inputs, please share. Thanks.

**Comment by justinbmeyer** [comment]
I'd temporarily overwrite the XHR object similar to can-fixture and make sure it's called in the right way.

**Comment by prashantsharmain** [comment]
xhr is a private member inside the ajax module and I'm not sure if it could be mocked. What do you think?

`module.exports = namespace.ajax = function (o) {
        var xhr = $.xhr(), timer, n = 0;
    var deferred = {};
        ...
}`

**Comment by justinbmeyer** [comment]
I'm talking about XMLHTTPRequest
