### ISSUE TITLE
Shorthand for assigning non-enumerable

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-util#101]
``` js
assignNonEnumerable(canEvent, {
  makeHandlerArgs: function(){ ... }
  handlers: function(){ ... }
  flush: function(){ ... }
})
```

This would be useful for reducing a lot of repeat code all over CanJS.  Just search for `enumerable: false` and see what comes up.

**Comment by matthewp** [comment]
What are these API methods?

**Comment by justinbmeyer** [comment]
These are internal methods.

**Comment by chasenlehara** [comment]
https://github.com/canjs/can-util/pull/117
