### ISSUE TITLE
Change types to use a property Symbol check?

### ISSUE THREAD

**Issue by BigAB** [canjs/can-util#103]
RE: https://github.com/canjs/can-util/blob/master/js/types/types.js#L8-L28
This way of declaring your object is "typeLike" seems strange and possibly error prone to me.

I wonder if it would be worth it to, rather than modules overwriting the individual functions, have instances get 
a special Symbol property on their prototype, similar to declaring an interface: 

``` js
CanDefine.prototype[Symbol.for("isMapLike")] = true;
CanMap.prototype[Symbol.for("isMapLike")] = true;
CanList.prototype[Symbol.for("isMapLike")] = true;
CanList.prototype[Symbol.for("isListLike")] = true;
```

_*we may actually want to namespace the symbols a bit like `Symbol.for("can.isMapLike")` just to be safe_

Then the type methods could just check for those symbols on an instance:

``` javascript
/**
   * @function can-util/js/types/types.isMapLike isMapLike
   * @signature `types.isMapLike(obj)`
   *   Returns true if `obj` is an observable key-value pair type object.
   *
   * @return {Boolean} `true` if the object is map like.
   */
  isMapLike: function(obj){
    return obj[Symbol.for("can.isMapLike")];
  },
```

One benefit is that a class could declare itself 'MapLike' without requiring can-util, further loosening the coupling
Another is that, with the simplicity, if one module accidentally screws it up:

``` js
var types = require("can-util/js/types/types");
types.isMapLike = function(obj){
  return obj instanceof MySpecialMap;
};
types.DefaultMap = MySpecialMap;
```

it wouldn't break for everything else.

Of course, can-util would need to ship with a Symbol [polyfill](https://github.com/medikoo/es6-symbol) for this to work in all supported browsers. Maybe that's reason enough not to do it.

**Comment by matthewp** [comment]
Symbols would be cool, but can-util/dom/data/data works too.  I agree that this is the way to go, to avoid having to wrap an object, which makes this not work:

``` js
var types = require("can-util/js/types/types");
var isMapLike = types.isMapLike;

steal.done().then(function(){
  isMapLike(someMap); // false 
});
```

**Comment by justinbmeyer** [comment]
While working on my 3.0 roadmap, I've discovered a problem with Symbols ... they will only work well for types we define.  Say someone pulls in a custom promise implementation that we want observable.  On Promise libraries that don't have a `Promise.prototype` that we can inject a symbol, it will be very hard for the promise to be identified as a promise to the CanJS system.

While I think symbols are useful, we're going to have to support overwriting `can-operate` methods as well.

**Comment by phillipskevin** [comment]
This was closed with `can-reflect`.
