### ISSUE TITLE
should .set("values",[]) trigger a "values" event if the value is really the same

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-util#105]
If you call:

`attr.set(el, "values",[])`

twice, a "values" event is still fired .. indicating a change in the property.  Is this correct behavior?

**Comment by matthewp** [comment]
You mean the "values" event is fired twice? I think that's correct behavior, yes. A property event should fire every time the property changes, even if it changes to the same deepEqual value. It's up to the listener (in this case a compute) to figure out if the event is noteworthy or not.

Maybe I'm wrong though, is there a precedence for a sort of property event in the DOM world?

**Comment by justinbmeyer** [comment]
But there is no actual change in the DOM.

**Comment by matthewp** [comment]
What are you calling "the DOM"?  If a property is set on an element, that's a change.

**Comment by justinbmeyer** [comment]
`values` doesn't actually set a property ... it sets the `.selected` property on `<option>`s.  Those selected properties aren't changing.

**Comment by matthewp** [comment]
My point is that this isn't a `change` event, it's a property event. We've introduced the concept of property events and I think they should work the same across the board.  Whether `values` actually sets a property or not is an implementation detail, the API is `attr.set` so my expectation is the same sort of behavior for bindable properties.

So I would expect:

``` js
el.addEventListener("foo", function(){
  // foo event!
});

el.foo = "bar";
el.foo = "bar";
```

I would expect this handler to fire twice, because the event system shouldn't care about the value, only that the property was set.  Another layer should handle diffing the value.

**Comment by justinbmeyer** [comment]
@matthewp I think we discussed this and came to the conclusion that because the DOM doesn't fire multiple change events we'd have this fire once.  Do you know if this was fixed?

**Comment by matthewp** [comment]
I don't think it was.

**Comment by matthewp** [comment]
I know that we had a private conversation and came to that conclusion but I don't remember why. Reading this issue now I still feel that firing the event twice is the correct behavior. Do you remember the rationale?

**Comment by matthewp** [comment]
I'm confused by this issue. `attr.set("values")` doesn't cause a `values` even. Changes in data shouldn't trigger a values event, only user triggered changes such as selecting an option should trigger a values event.

**Comment by justinbmeyer** [comment]
> the rationale?

@matthewp both the DOM and our observables work like this.  Events should fire only when there is a change, not when the setter is called.

**Comment by justinbmeyer** [comment]
`.setAttribute("foo", "bar")` fires an `attributes` DOM mutation, but calling it again does not.
