### ISSUE TITLE
Inserted event not fired for empty frag when can-jquery is present

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-util#119]
If jquery is present, this test fails: https://github.com/canjs/can-util/blob/master/dom/mutate/mutate-test.js#L17-L34

**Comment by matthewp** [comment]
I assume you mean can-jquery, right?

**Comment by phillipskevin** [comment]
Yes. Thanks.

**Comment by phillipskevin** [comment]
Closed by https://github.com/canjs/can-jquery/issues/28.
