### ISSUE TITLE
ajax doesn't support jQuery ajax options. 

### ISSUE THREAD

**Issue by green3g** [canjs/can-util#138]
Properties like `beforeSend`, `headers` passed to `can.ajax` are ignored. 

http://jsbin.com/vasexixevi/edit?html,js,console,output

[The docs](https://v3.canjs.com/doc/can-util/dom/ajax/ajax.html) still say 

> ajax( settings ) is used to make an asynchronous HTTP (AJAX) request similar to http://api.jquery.com/jQuery.ajax/jQuery.ajax.

Ultimately, I don't need all of the jquery functionality, I just need a way to set custom headers on the request.

**Comment by justinbmeyer** [comment]
It does support a similar API, but not close to as many features. It's designed only to support the bare minimum features needed for CanJS.  Headers and beforeSend aren't needed for this. 

I'm not sure we should add these sorts of things.

**Comment by green3g** [comment]
Okay, that's fair. This can be closed, I had misunderstood. I can just use jquery's ajax method for those features.

**Comment by green3g** [comment]
Reopening this because I just found a similar issue. I was trying to get `ajax` to send a `POST` request, and it wasn't working. Its because the parameter for changing the request method on ajax requests is `settings.type`. This is fine, but according to the docs:

> settings {Object}: Configuration options for the AJAX request. The list of configuration options is the same as for jQuery.ajax.

The request type variable for jquery is `method`. It wasn't hard to figure out why the code wasn't working by looking thorugh the ajax code, but it would be helpful if the docs detailed _which_  jquery properties are available and which ones are not, and also to make the distinction that `type` is used instead of `method` for changing the request method.

**Comment by ilyavf** [comment]
This is fixed with https://github.com/canjs/can-util/pull/192
Will be released after `3.3.0` either as a minor or a patch release.
