### ISSUE TITLE
deepAssign()'ing js/js causes two unrelated Types objects.

### ISSUE THREAD

**Issue by bmomberger-bitovi** [canjs/can-util#155]
```javascript
> steal("can-util").then(c => window.CanUtil = c);
<- Promise
> steal("can-util/js/types/").then(c => window.CanTypes = c);
<- Promise
> CanUtil.types === CanTypes
<- false
```

This is important because `DefaultMap` can be set on the Types object by, e.g., importing `can-define/map/`, but that doesn't then get reflected in the `can-util.types` / `can.types` object (these two references are to the same object).

I suggest overwriting `deepAssign()` in can-util.js for any objects that contain values set by other libraries.

**Comment by justinbmeyer** [comment]
It doesn't look like `can-util/js/js` is deep assigning: 

https://github.com/canjs/can-util/blob/master/js/js.js

Has this been fixed?

**Comment by justinbmeyer** [comment]
It's happening here: https://github.com/canjs/can-util/blob/master/can-util.js#L5

I don't think we should use deepAssign.  Why wasn't assign enough?

**Comment by matthewp** [comment]
Assign should be enough, agreed: 👍

**Comment by bmomberger-bitovi** [comment]
Closed via https://github.com/canjs/can-util/pull/157.  Thanks @phillipskevin
