### ISSUE TITLE
Two way view binding doesn't work properly in IE11 (Windows 8.1)...

### ISSUE THREAD

**Issue by imjoshdean** [canjs/can-util#178]
...if two way binding is on an input and you manually manipulate the value.

Example: http://jsbin.com/nuhelabisa/edit?html,css,js,console,output

What should happen: After manipulating the value and blurring the element, the `set` function on `value` should be called.

What does happen: nothing.

This only seems to be happening in the Windows 8.1 version of IE11.

**Comment by matthewp** [comment]
You're expecting that a keyup on the input should cause the `value` property's setter to be called, is that right? That doesn't seem to be happening in Chrome either... I think I'm misunderstanding the bug here.

**Comment by phillipskevin** [comment]
I think what @imjoshdean is expecting is:
1. the user types in the input
2. the `keyup` handler sets `input.value`
3. the user clicks out of input (triggering a `blur`)
4. the `set` is triggered

**Comment by matthewp** [comment]
That's what I thought as well, but my confusion is if this is a bug report for just IE11? Because I can't see this working that way any where.

**Comment by phillipskevin** [comment]
It's working for me in Chrome:

![blur](https://cloud.githubusercontent.com/assets/5851984/22482398/6b25ee56-e7be-11e6-871f-daba75526a0b.gif)

**Comment by imjoshdean** [comment]
It seems to be working just fine for me in other browsers, our client has reported the problem just in this specific instance of IE11.

**Comment by matthewp** [comment]
What am I doing wrong?

![thebug](https://cloud.githubusercontent.com/assets/361671/22482504/4dc9af38-e7c7-11e6-97f2-7bc9c02f9e1a.gif)

**Comment by phillipskevin** [comment]
Not sure. Looks like you're doing the same thing as me. Maybe a different version of Chrome? I'm using 56.

**Comment by imjoshdean** [comment]
Hm, I what version of Chrome are you on. I passed this by @ilyavf who was on 55.x.x and had an issue, but upgrades and it was fine on 56.x.x, I'm on 57.x.x myself.

**Comment by justinbmeyer** [comment]
@imjoshdean Do you remember what the resolution was for this?  I remember looking into it w/ you, but couldn't remember what was decided.  I think it was something like "jquery doesn't even try to solve it ... because it's almost impossible to solve the right way ... so maybe we punt".

**Comment by justinbmeyer** [comment]
Closing because I think it's not possible to fix this.  (feature detection is impossible)
