### ISSUE TITLE
Document calling js/each/each with an object

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-util#208]
The docs show that `each` only works with an Array-Like, but it actually works with objects also:

```
can.each({foo: 'bar', abc: 'xyz'}, function(val, key) {
  console.log(key + ': ' + val);
});

// "foo: bar"
// "abc: xyz"
```

We should document that it works with an array or an object just like we had documented in 2.3: https://v2.canjs.com/docs/can.each.html

This is related to https://github.com/canjs/canjs/issues/3116.

**Comment by sarathnair** [comment]
Fixed via #211
