### ISSUE TITLE
Possible memory leak?

### ISSUE THREAD

**Issue by sszabolcs** [canjs/can-util#212]
Hello!

It seems to me that can-util/dom/data/data causes a memory leak.
In data.js there is a variable 'data' that stores objects by id.
As I could understand the problem lies in not cleaning the 'data' variable.

To put everything in context: we have a quite large app (19 000 LOC) that is built with CanJS 2.x.
We are happy with it and started to migrate to 3.x.
We are at the final steps of migration and now we realized that with CanJS 3 we have a memory leaking problem.
I've created a small sample app that compares CanJS 2 and 3 regarding memory usage:
[gist link](https://gist.github.com/sszabolcs/3eb7cc415e18c64cb88a8dcd0002732b)

1. Open index_canjs2.html and with dev tools Timeline record memory usage (start recording with a GC).
2. Click on Insert/Remove for a few times.
3. Before stopping Timeline recording call GC, then stop recording.
For example if I click on Insert/Remove for three times I can see on Timeline that there are exactly the same number of listeners (3) and nodes (70) in the begining as in the end.

Repeating these steps with index_canjs3.html show that the number of listeners grow gradually (4->10)!
If you put a breakpoint at the 753. row of can.all.js and analyze the content of variable 'data' (in Closure)
after you click on Insert, you can see, that after a few "click on Insert/click on Remove" cycle 'data' keeps growing.
Initially - at the first click on Insert - there are 3 items in it.
Clicking Insert for the second time the 'data' variable contains 8 item.
When I click on Insert for the sixth time 'data' contains 28 objects!
No object gets removed from it.

This causes a memory leak: there are detached HTMLAnchorElements which cannot be GC-d because 'data' keeps reference for objects (canAttributesObserver, MutationObserver) which reference these HTML objects.
Shouldn't 'data' contain only objects that are somehow related to objects live in the DOM?
Is there something I'm doing wrong regarding the component insertion and removal?

**Comment by justinbmeyer** [comment]
@phillipskevin if you can put this into a jsbin and try reducing it, I can take a look.  Thanks!

**Comment by justinbmeyer** [comment]
I created this page which work's inside `canjs/canjs`:

```html
<!DOCTYPE html>
<html>
    <head>
        <title>CanJS 3.0 memory test</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <script type="text/stache" id="my-component">
            value of test property: {{testProperty}}
        </script>

        <script type="text/stache" id="content-using-my-component">
            <div id="my-component-container" />

            {{#if myCompInserted}}
                <a ($click)="removeMyComp()" href="javascript://">Remove</a>
            {{else}}
                <a ($click)="insertMyComp()" href="javascript://">Insert</a>
            {{/if}}
        </script>

        <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
<script src="./node_modules/steal/steal.js">
var Component = require("can-component"),
	DefineMap = require("can-define/map/map"),
	stache = require("can-stache");

var MyComponentVM = DefineMap.extend({
    testProperty: { type: "string", value: "init test property value" }
});

Component.extend({
    tag: "my-component",
    view: stache.from("my-component"),
    ViewModel: MyComponentVM
});

var myCompRenderer = stache("<my-component />");

var TestVM = DefineMap.extend({
    myCompInserted: { type: "boolean", value: false },

    insertMyComp: function () {
        var myCompFrag = myCompRenderer();
        $("#my-component-container").html(myCompFrag);
        this.myCompInserted = true;
    },

    removeMyComp: function () {
        $("#my-component-container").empty();
        this.myCompInserted = false;
    }
});

var template = stache.from("content-using-my-component");
var frag = template(new TestVM());
document.body.appendChild(frag);

</script>
    </body>
</html>
```

**Comment by justinbmeyer** [comment]
My guess is that the `attributes` event isn't being cleaned up correctly: https://github.com/canjs/can-stache-bindings/blob/master/can-stache-bindings.js#L112


It should be unbound around here: https://github.com/canjs/can-stache-bindings/blob/master/can-stache-bindings.js#L146

**Comment by justinbmeyer** [comment]
Unbinding fixed one `attributes` event binding.  However, there's another one:

https://github.com/canjs/can-stache-bindings/blob/master/can-stache-bindings.js#L337

This one can probably listen for `removed` and clean it up there.



It also looks like the `viewModels` and `controls` are being leaked.  We should be cleaning those up.    My guess this is component.

**Comment by justinbmeyer** [comment]
I think we should have our stuff clean itself up no matter what, but also probably have `data` clean itself up with mutation observers.

We'll need data to clean itself up "at the end" of everything being notified.  This is because someone might listen to `removed` and expect data still in `domData`.

This means we will need some sort of "after everything" handlers in:

https://github.com/canjs/can-util/blob/master/dom/mutation-observer/document/document.js

This is so `domData` can get called back after all "removed" events have been fired.

**Comment by phillipskevin** [comment]
@sszabolcs This fix is released with [v3.3.3](https://github.com/canjs/can-util/releases/tag/v3.3.3). Can you try this out in your app and please let us know if you are still seeing an issue?

**Comment by sszabolcs** [comment]
@phillipskevin Of course, I'm gonna try this out now and will let you know what the results were. Thank you for the quick fix!

**Comment by sszabolcs** [comment]
@phillipskevin I've tested the fix. The memory leak seems to be solved but now another problem arises. I'm getting the following exception:
![image](https://cloud.githubusercontent.com/assets/18262711/24406728/2cbc484a-13c9-11e7-958f-b1929a753636.png)
This exception is raised when I "switch views" and so remove components from the dom. domData gives back 'undefined' value for the 'controls' data. The problem only arises when the can-jquery module is loaded as a dependency.

**Comment by phillipskevin** [comment]
Thanks. I'll look into this today.

**Comment by phillipskevin** [comment]
@sszabolcs there are new releases of [can-control](https://github.com/canjs/can-control/releases/tag/v3.0.9) and [can-jquery](https://github.com/canjs/can-jquery/releases/tag/v3.0.5) to resolve this issue. Hopefully everything is working for you again now.

**Comment by sszabolcs** [comment]
@phillipskevin thank you for the fix. The error disappeared but there is a memory leak if I have can-jquery imported. Without can-jquery there is no memory leak. I need can-jquery so that my binded Map updates on a 'change' event triggered on an html element. So it would be great if you could help me getting rid of this leak.

Here I have a test project which you can use to debug:
[GitHub](https://github.com/sszabolcs/CanJS3_memory_test)

can-jquery.eventHandler does not get cleaned up as I see:
![image](https://cloud.githubusercontent.com/assets/18262711/24503739/a63c9716-1553-11e7-8b94-a872cd3c28ea.png)

**Comment by phillipskevin** [comment]
@sszabolcs Thanks for reporting, I opened https://github.com/canjs/can-jquery/issues/52 for this.
