### ISSUE TITLE
Deprecate js/is-array/ and js/is-string/

### ISSUE THREAD

**Issue by chasenlehara** [canjs/can-util#225]
Both of these are simple one-liners. Is there any reason not to deprecate them and remove them in a future release?

https://github.com/canjs/can-util/blob/4c55ab3297c334998a6c0d8aa2c784cfac94ddac/js/is-array/is-array.js#L2

https://github.com/canjs/can-util/blob/4c55ab3297c334998a6c0d8aa2c784cfac94ddac/js/is-string/is-string.js#L20

**Comment by matthewp** [comment]
isArray for sure. Probably the other as well. Would have to be in can-util 4.0 though.

**Comment by chasenlehara** [comment]
We could [deprecate it in a minor release](http://semver.org/#how-should-i-handle-deprecating-functionality) and remove it in the next major, right?

**Comment by matthewp** [comment]
We could, possibly. We should probably have a DoneJS level discussion about how to handle deprecations. I know that some frameworks wait for 2 major releases; deprecate in a major (with warnings) and remove in the next major. I lean towards the minor release strategy like you mentioned. I've wondered the same thing about some StealJS deprecations.

**Comment by chasenlehara** [comment]
Added to [tomorrow’s contributors meeting](http://forums.donejs.com/t/donejs-contributors-meeting-2017-03-31/589/3). 🙂

**Comment by andrejewski** [comment]
What was the resolution of the meeting?

**Comment by justinbmeyer** [comment]
We decided to deprecate

**Comment by chasenlehara** [comment]
@andrejewski Sorry if my notes from http://forums.donejs.com/t/donejs-contributors-meeting-2017-03-31/589/9 weren’t clear about us deciding to deprecate both. 😕
