### ISSUE TITLE
All object-mutation functions in can-util should use strict mode.

### ISSUE THREAD

**Issue by bmomberger-bitovi** [canjs/can-util#230]
E.g. `can-util/js/assign/assign` is currently non-strict, and doesn't throw errors when a can-defined object gets non-writable properties set on it.

**Comment by justinbmeyer** [comment]
the change is really easy, but we should make sure everything works by testing it against canjs/canjs's tests.

**Comment by andrejewski** [comment]
Adding only `'use strict';` *inside* the assign function breaks an attribute event test. That issue may be related to https://github.com/canjs/can-util/pull/49 as the error case is similar.

**Comment by justinbmeyer** [comment]
There's probably something wrong with .attr then.
