### ISSUE TITLE
Update can-ajax and its dependancies to the new external modules

### ISSUE THREAD

**Issue by imaustink** [canjs/can-util#234]
`can-ajax` has been moved to its own repository. All references to `can-ajax` and its dependencies must be updated to use the new NPM modules.

**Comment by morrme** [comment]
@imaustink  Is this something you could use an extra hand with?

**Comment by imaustink** [comment]
Hey @morrme! Sorry I missed your comment until now! I think I've got it, there's actually an open PR #235. It's waiting on [`can-globals`](https://github.com/canjs/can-globals/issues/1) which is still an open RFC. Feel free to comment if you have any input!

**Comment by imaustink** [comment]
Closed by https://github.com/canjs/can-util/pull/235
