### ISSUE TITLE
isEmptyObject returns true when there is a non-enumerable property

### ISSUE THREAD

**Issue by matthewp** [canjs/can-util#24]
``` js
QUnit.test("Objects with non-enumerable props are false", function(assert){
    var obj = {};
    Object.defineProperty(obj, "foo", {
        enumerable: false,
        value: "bar"
    });

    assert.equal(isEmptyObject(obj), false, "Not an empty object");
});
```

This test fails, I think it should work though.  We could make it work with this pseudo-code:

``` js
var props = Object.getOwnPropertyNames(obj);
return !props.length;
```

For browsers that support getOwnPropertyNames.

**Comment by matthewp** [comment]
cc @justinbmeyer

**Comment by prashantsharmain** [comment]
@matthewp Should we take into account the prototype chain as well? For example, 

```
while (obj !== Object.prototype) {
    if (Object.getOwnPropertyNames(obj).length) {
        return false;
    }
    obj = Object.getPrototypeOf(obj);
}
return true;

```

The following test fails, however, with this change:

can-util/js/is-empty-object/is-empty-object: Returns true for custom objects with no props (1, 1, 2)Rerun646200 ms
is empty@ 646191 ms
Expected:  
true
Result: 
false
Source: 
    at Object.<anonymous> (http://192.168.0.184:8080/js/is-empty-object/is-empty-object-test.js:33:9)
    at runTest (http://192.168.0.184:8080/node_modules/qunitjs/qunit/qunit.js:843:28)
    at Object.run (http://192.168.0.184:8080/node_modules/qunitjs/qunit/qunit.js:828:4)
    at http://192.168.0.184:8080/node_modules/qunitjs/qunit/qunit.js:970:11
    at process (http://192.168.0.184:8080/node_modules/qunitjs/qunit/qunit.js:629:24)
    at begin (http://192.168.0.184:8080/node_modules/qunitjs/qunit/qunit.js:611:2)

Any thoughts?

**Comment by matthewp** [comment]
@prashantsharmain I think based on our discussion today that this isn't actually a bug.  Let me know if you feel otherwise. But non-enumerable properties probably shouldn't could towards the count.

**Comment by prashantsharmain** [comment]
@matthewp I agree with you. I reviewed similar implementations in other libraries. None of them check for non-enumerable properties:

[https://api.jquery.com/jQuery.isEmptyObject/](https://api.jquery.com/jQuery.isEmptyObject/)
[https://lodash.com/docs#isEmpty](https://lodash.com/docs#isEmpty)
[http://underscorejs.org/#isEmpty](http://underscorejs.org/#isEmpty)

However, their API documentation clearly spells this out.

I'll update our docs and submit a PR.

**Comment by matthewp** [comment]
👍
