### ISSUE TITLE
Custom event registry

### ISSUE THREAD

**Issue by andrejewski** [canjs/can-util#249]
Currently, custom events override `can-util/dom/events/event.js` `add/removeEventListener` when required. However this is a problem because:

- Make nested calls and many functions
- Overriding is bad
- The custom event cannot be easily removed (tests suffer)

So we need a way of registering custom events. I propose:

```js
var events = require('can-util/dom/events/events');
var customEvent = require('can-my-custom-event');
events.addCustomEvent(customEvent);
events.removeCustomEvent(customEvent);
```

`customEvent` conforms to this API:
```js
{
  eventName: string,
  applyEventListener: boolean,
  addEventListener: function (
    eventName: string,
    listener: function, 
    ...otherAddEventListenerArgs) {},
  removeEventListener: function (
    eventName: string,
    listener: function,
    ...otherRemoveEventListenerArgs) {},
}
```

Add we say these things:
- An error is thrown if a custom event registers on a taken name
- The addEventListener/removeEventListener `this` is the DOM element

Open to suggestions.

**Comment by matthewp** [comment]
Looks good to me!  I think @justinbmeyer might have some concerns about this being a global map.  I'm not sure where else to put this type of information except for in a global map though.

**Comment by justinbmeyer** [comment]
What does applyEventListener do? Should addEventListener/remove have the handler specified?

**Comment by andrejewski** [comment]
`applyEventListener` when `true` calls the original `domEvent.addEventListener()` as well as the custom event's addEventListener. This is an option because some custom events may not want to actually attach a listener to the DOM, but `can-event-radiochange` needs to in order to work properly. Here's what it means in code:

```js
var old = domEvents.addEventListener;
domEvents.addEventListener = function (eventName) {
  if (eventName === customEvent.eventName) {
    radioChange.addEventListener.apply(this, arguments);
    if (!radioChange.applyEventListener) {
      return;
    }
  }
  return old.apply(this, arguments);
};
```

Of course we will be using a Map<eventName, customEvent> but the conditional is the important bit here.

**Comment by matthewp** [comment]
Another idea, this sounds very familiar with the customElements idea, which has its own registry. You can see the docs for that here: https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry. I implemented an identical project for custom attributes: https://github.com/matthewp/custom-attributes/blob/master/attr.js

If we want to provide a way to create your own registry a similar api could work:

```js
var customEvents = require("can-custom-events");

customEvents.define("myevent", function(){
  // Add event listener stuff

  return function(){
    // teardown stuff
  };
});
```

With the first param being optional.  If omitted `fn.eventName` is used.

To create your own registry:

```js
var CustomEventsRegistry = require("can-custom-events").Registry;

var reg = new CustomEventsRegistry();

var myEvent = function(){

};

myEvent.eventName = "myevent";

reg.define(myEvent);
```

**Comment by andrejewski** [comment]
[DoneJS Contributors Meeting discussion](http://forums.donejs.com/t/donejs-contributors-meeting-2017-04-28/610/3)

- We should have a good way to have multiple registries such as global, document fragment, and template-levels.
- Look into Custom events API: https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry
- We should do the right thing regarding returning a disconnect from the addEventListener event so we can cleanup safely.
- Think about how we can incorporate jQuery++ events into the new interface.

**Comment by andrejewski** [comment]
# Revised API

For multiple registries, we need an abstract CustomEventRegistry class:

```js
class CustomEventRegistry {
  addCustomEvent ([eventName: String,] customEvent: CustomEvent);
  removeCustomEvent ([eventName: String,] customEvent: CustomEvent);
  
  /*
  It is *abstract* for persistence to fit the domain. 
  `domEvents`, fragments, and templates will persist 
  however makes sense by overriding the methods:
  */
  // this is a map
  setCustomEvent (eventName: String, value: any);
  getCustomEvent (eventName: String): customEvent: CustomEvent;
  
  // this is a map of arrays
  getHandlersFor (eventName: String): Array<CustomEventHandler>;
  removeAllHandlersFor (eventName: String);
  addHandlerFor(eventName: String, handler: CustomEventHandler);
  removeHandlerFor(eventName: String, handler: CustomEventHandler);
}
```

`CustomEvent` is an interface:

```js
interface CustomEvent {
  defaultEventName: String;
  applyEventListener: Boolean;
  createHandler (
    eventName: String,
    listener: Function,
    ...addEventListenerArgs
  ): CustomEventHandler;
}
```

`CustomEventHandler` is also an interface:

```js
interface CustomEventHandler {
  attach ();
  detach ();
}
```

Note: `CustomEventHandler` is not a plain function because `createHandler()` should not have any side-effects. The registry will do the smart thing and call `attach` itself when it makes sense. The other nice thing is 💥 we can remove/attach/re-remove/re-attach as much as we want. Also test more better.

Please let me know if there are questions or concerns.

**Comment by matthewp** [comment]
So, **addHandlerFor** and **removeHandlerFor** would be override by whatever is storing them (either in a global map or in a per-template map, etc.

Since these are going to be used in code inside of add/removeEventListener functions, addHandlerFor and removeHandlerFor need to take both the eventName and the listener function.

**Comment by andrejewski** [comment]
This discussion is followed by a proposal to the main Can.js repo: https://github.com/canjs/canjs/issues/3210

**Comment by andrejewski** [comment]
[`can-dom-events`](https://github.com/canjs/can-dom-events) went 1.0.0 yesterday, closing.
