### ISSUE TITLE
Steal Specific syntax in enter-leave.js breaks with webpack

### ISSUE THREAD

**Issue by BigAB** [canjs/can-util#258]
This line:
https://github.com/canjs/can-util/blob/master/dom/events/delegate/enter-leave.js#L13

Breaks with webpack.

**Comment by matthewp** [comment]
Please fix :)

**Comment by BigAB** [comment]
Honestly, give me a few seconds 😄

**Comment by matthewp** [comment]
We should probably have some type of lint rule that prevents using that syntax.
