### ISSUE TITLE
Events on Disabled Elements in FF and IE

### ISSUE THREAD

**Issue by christopherjbaker** [canjs/can-util#294]
The [basic disabled insertion - no MutationObserver](https://github.com/canjs/can-util/blob/master/dom/events/inserted/inserted-test.js#L33-L48) test periodically stalls, never running it's `start()`. I have narrowed down the issues to [this call](https://github.com/canjs/can-util/blob/master/dom/events/events.js#L54) to `dispatchEvent`. This line is run, but the listener does not fire (I have confirmed that the listener is added prior to this call, even so much as putting a `setTimout(1000)` delay).

When running this test in isolation, it seems to fail about 1 in 30. When running the full canjs test suite, it is much more common, around 1 in 3. I am not sure why this would vary.

I have only been able to recreate it in firefox, both 51 and 54. I believe this is related to [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=329509), and I'm not sure how this can be fixed, other than disabling this test for FF, and possibly adding a warning when attempting to run an event on a disabled element.

Removing the [`input.disabled = true;`](https://github.com/canjs/can-util/blob/master/dom/events/inserted/inserted-test.js#L36) removes the stall (as the element is no longer disabled), though the ["re-enable"](https://github.com/canjs/can-util/blob/master/dom/events/events.js#L52) doesn't seem to make a difference.

**Comment by andrejewski** [comment]
@christopherjbaker Was the "re-enable" branch called?

**Comment by christopherjbaker** [comment]
If you mean "was `this.disabled = false;` actually run?", then yes. I actually put that right before dispatchEvent, to make sure it was run no matter what.

**Comment by andrejewski** [comment]
Okay, just checking. I'd like to know more about this behavior as we move forward with `can-dom-events` which replaces `can-util/dom/events`.
