### ISSUE TITLE
Warning every time can-util/dom/events/ runs

### ISSUE THREAD

**Issue by matthewp** [canjs/can-util#298]
This code: https://github.com/canjs/can-util/blob/d00eb3c5fec7eabfc6297e1e129694f04585c7f6/dom/events/events.js#L96 always causes a warning that stems from this: https://github.com/canjs/can-util/pull/295/files

**Comment by matthewp** [comment]
We should some how prevent the warning in this case, warning should only come from user code.

**Comment by andrejewski** [comment]
Fixed by https://github.com/canjs/can-util/pull/299
