### ISSUE TITLE
Using deep-assign instead of assign on dom/events/attributes/attributes.addEventListener

### ISSUE THREAD

**Issue by cherifGsoul** [canjs/can-util#308]
It seems that we need a clone for ```mutation``` object [here](https://github.com/canjs/can-util/blob/master/dom/events/attributes/attributes.js#L43) in order to fix [this](https://github.com/canjs/can-util/pull/306), I tested localy the usage of ```deep-assign``` (clone) instead of ```assign``` and all tests passe for ```can-util```.

**Comment by cherifGsoul** [comment]
here is a branch with the change https://github.com/canjs/can-util/blob/deep_assing_for_dom_ev_attr_308/dom/events/attributes/attributes.js

**Comment by justinbmeyer** [comment]
When you say "fix this" ... what do you mean exactly?  Why does the mutation object need to be deep cloned?

**Comment by cherifGsoul** [comment]
@justinbmeyer I mean fix the issue in the referenced PR. 
It seems that the ```MutationRecord``` properties are not enumerable, I did a check with ```Object.prototype.propertyIsEnumerable```.

**Comment by andrejewski** [comment]
@cherifGsoul I am having trouble following this problem across the PRs and issues around it. Would you be able to summarize what needs changed and why? (Potentially closing out this issue, and opening a new, longer one.)

Changing the behavior of `can-util/js/assign` is quite dangerous as it is used everywhere and can easily break dependent projects. There are changes to `assign` we have to wait until 4.0 to make and this may be one of those types of changes.

**Comment by cherifGsoul** [comment]
@andrejewski The issue is if we want to rewrite can-util/assign to mimic the native Object.assign it will break dom/events/attributes/attributes.addEventListener and the simple assign (like the actual) works fine.

I agree with you that the changes on assign can wait till 4.0 and write it with this https://github.com/canjs/canjs/issues/3426 in mind.
I close this issue and write a detailed one later.
