### ISSUE TITLE
handle on:camelCaseProp in setAttribute

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-util#318]
For https://github.com/canjs/can-stache-bindings/issues/229, we need to be able to have properties like `on:someMethod="someProp"` work. We need to handle this here: https://github.com/canjs/can-util/blob/master/dom/attr/attr.js#L507 to prevent errors:

![image](https://user-images.githubusercontent.com/5851984/28757510-629d3c16-754a-11e7-8f5f-8afe5112b672.png)

**Comment by justinbmeyer** [comment]
Let's have an encoding that works then.

**Comment by phillipskevin** [comment]
Ok, I think that makes sense. Do you also want to revisit how we're encoding spaces? Spaces only work currently because it goes through this [code](https://github.com/canjs/can-util/blob/master/dom/attr/attr.js#L507-L516) to use `setAttributeNode`, which makes `dom/attr` have some specific code for our binding syntaxes.

**Comment by phillipskevin** [comment]
This was handled by https://github.com/canjs/can-view-parser/releases/tag/v3.5.0.
