### ISSUE TITLE
Get skipped tests passing

### ISSUE THREAD

**Issue by andrejewski** [canjs/can-util#320]
Some tests where being skipped when `window.eventsBubble` was false, the problem is the ordering of tests meant it was never true.

- [dom/attr/attr-test](https://github.com/canjs/can-util/blob/30272b5c7eb3f3239bf9ec69379b7ee85675f45f/dom/attr/attr-test.js#L678)
- [dom/mutate/mutate-test](https://github.com/canjs/can-util/blob/30272b5c7eb3f3239bf9ec69379b7ee85675f45f/dom/mutate/mutate-test.js#L63)

Note that these tests should be re-evaluated as to whether they are necessary and inline with the scope of current concerns.

**Comment by bgando** [comment]
Most recent failing build before skips were added: https://travis-ci.org/canjs/can-util/builds/260327357

### Windows 10 internet explorer 11.0 
Sauce Labs Job: https://saucelabs.com/jobs/43a5f6dbbcef4094924f6f152f9b3f32
![image](https://user-images.githubusercontent.com/3348231/29939135-e466945a-8e58-11e7-9c5d-82aad350a27d.png)

Passed: false (358 / 361)

### OS X 10.11 safari 10.0 

Sauce Labs Job: https://saucelabs.com/jobs/88ee92e81cac43bc8c0073325fb6b8bf
![image](https://user-images.githubusercontent.com/3348231/29939742-e3ac4422-8e5a-11e7-9f6c-d7366394c319.png)

Passed: false (359 / 363)

Failing test:
https://github.com/canjs/can-util/blob/30272b5c7eb3f3239bf9ec69379b7ee85675f45f/dom/attr/attr-test.js#L678-L739

### iPhone 7 Simulator iOS 10.0 Safari 
Sauce Labs Job: https://saucelabs.com/jobs/6a176acdc57e49eeb6aeb52f9f933dec
![image](https://user-images.githubusercontent.com/3348231/29939799-1ff4517c-8e5b-11e7-9911-b055ffc637cc.png)

Passed: false (358 / 359)
Failing Test:
https://github.com/canjs/can-util/blob/30272b5c7eb3f3239bf9ec69379b7ee85675f45f/dom/mutate/mutate-test.js#L63-L82

**Comment by bgando** [comment]
### Windows 10, IE 11, cannot reproduce error:
![image](https://user-images.githubusercontent.com/3348231/30081564-ace2573e-9255-11e7-8152-fe0c61490fcd.png)
![image](https://user-images.githubusercontent.com/3348231/30081585-bcad00ba-9255-11e7-9ced-5b74a95a3aff.png)

### OS X 10.11 safari 10.0, can reproduce the attr/mutate error only
https://saucelabs.com/beta/tests/c91b8ed4785a46569b33f737f6224375

### iPhone 7 Simulator iOS 10.0 Safari, can reproduce the attr/mutate error only
https://saucelabs.com/beta/tests/4d84bd9ede8e4b5495838f5bdb69b581

**Comment by bgando** [comment]
This issue will become part of a bigger re-organization of can-util's testing strategy.
