### ISSUE TITLE
can.isEmptyObject returns false for empty can.Maps

### ISSUE THREAD

**Issue by mjstahl** [canjs/can-util#33]
I am not sure what this would break, but because the function is namespaced with `can` I expected when applied to an empty can.Map the result would be `true`, because much of canjs is built on observables. 

``` js
x = new can.Map({});
can.isEmptyObject(x);
//-> false
```

**Comment by matthewp** [comment]
can.isEmptyObject comes from jQuery. In can-util we have our own version, which is the same as jQuery's. It's not meant to special case can types.

**Comment by justinbmeyer** [comment]
I'd support some sort of hook that map/list can implement to make this happen. I think lodash has something similar. 

Closing and labeling "needs a hero". This isn't something th core team is going to pursue at this time.

**Comment by matthewp** [comment]
The hook is to make _data be enumerable: false

**Comment by justinbmeyer** [comment]
But that won't work for can-define/map/map (especially if we consider undefined values to be non existent).

**Comment by mjstahl** [comment]
Maybe I am naive, but couldn't we just do something like just use `.attr()` on the observable and couldn't the results?

**Comment by justinbmeyer** [comment]
You can, but that's sort of a separate issue. The central issue is should these helpers "behave" for our special types.
