### ISSUE TITLE
Upgrade to can-globals 0.2.x

### ISSUE THREAD

**Issue by imaustink** [canjs/can-util#351]
Due to several circular dependencies, [upgrading to `can-globals@0.2.x` is blocked](https://travis-ci.org/canjs/can-util/builds/278828483?utm_source=github_status&utm_medium=notification).

```
can-util@3.10.8 /Users/austinkurpuis/bitovi/can-util
├─┬ can-event-dom-enter@1.0.1
│ ├─┬ can-dom-events@1.0.3
│ │ └── can-util@3.10.8  deduped
│ └── can-util@3.10.8 
├─┬ can-event-dom-radiochange@1.0.0
│ └── can-util@3.10.8  deduped
└─┬ can-types@1.1.1
  └── can-util@3.10.8  deduped
```

To solve this, I believe the following steps should be taken:
- [x] `can-cid`
  - [x] Merge [PR](https://github.com/canjs/can-cid/pull/22) to add `get-cid` to `can-cid`
  - [x] Release
  - [x] Release notes
- [x] `can-event-dom-enter`
  - [x] Update [`can-util/dom/data/data` reference](https://github.com/canjs/can-event-dom-enter/blob/b9bd76cb50ab8086d673afa6464cd3c6742df3c7/can-event-dom-enter.js#L3) to `can-dom-data-state`
  - [x]  Update [`can-util/js/cid/get-cid` reference](https://github.com/canjs/can-event-dom-enter/blob/b9bd76cb50ab8086d673afa6464cd3c6742df3c7/can-event-dom-enter.js#L3) to `can-cid/get-cid`
  - [x] Remove [`can-util/dom/events/events`](https://github.com/canjs/can-event-dom-enter/blob/8a287fb8d65c1c2abcea299dae4869e2284eda46/can-event-dom-enter-test.js#L5)
  - [x] Remove `can-util` as dependency
  - [x] Release
  - [x] Release notes
- [x] `can-event-dom-radiochange`
  - [x] Merge https://github.com/canjs/can-event-dom-radiochange/pull/9
  - [x] Update references to `can-util/dom/events/events` [here](https://github.com/canjs/can-event-dom-radiochange/blob/b95cdb33bb797445b02399cfdd6b844f814c9d70/can-event-dom-radiochange.js#L3) and [here](https://github.com/canjs/can-event-dom-radiochange/blob/ea15c86d2f7ae3f1c9132ff2acd552d9669fb9f6/can-event-dom-radiochange-test.js#L5)
  - [x] Update [`can-util/dom/data/data` reference](https://github.com/canjs/can-event-dom-radiochange/blob/b95cdb33bb797445b02399cfdd6b844f814c9d70/can-event-dom-radiochange.js#L4) to `can-dom-data-state`.
  - [x] Move `can-util/js/cid-map/cid-map` to `can-cid/map` and update [reference](https://github.com/canjs/can-event-dom-radiochange/blob/b95cdb33bb797445b02399cfdd6b844f814c9d70/can-event-dom-radiochange.js#L7)
  - [x] Remove `can-util` as dependency
  - [x] Test these changes locally with `can-stache-bindings`
  - [x] Release
  - [x] Release notes
- [x] `can-dom-events`
  - [x] Merge https://github.com/canjs/can-dom-events/pull/26
  - [x] Move `can-util/js/is-browser-window/is-browser-window` (potentially to `can-globals` or just use [can-is-browser-window](https://github.com/canjs/can-is-browser-window)?) and update [reference](https://github.com/canjs/can-dom-events/blob/17dfdcf39628ef39135d3e7fd889b3acd0db4823/helpers/util.js#L4)
  - [x] Remove `can-util` as dependency
  - [x] Release
  - [x] Release notes
-  [x] `can-types`
    - [x] Merge https://github.com/canjs/can-types/pull/32
    - [x] Split out `can-util/js/dev/dev` into `can-dev` and update [reference](https://github.com/canjs/can-types/blob/dc4f941ccd81333a5df43d96e485eee80135d160/can-types.js#L4)
    - [x] Remove `can-util` as dependency
    - [x] Release
    - [x] Release notes
- [x] `can-stache-binding`
   - [x] Update `can-event-dom-enter` and `can-event-dom-radiochange`
   - [x] Release
   - [x] Release notes
- [x] `can-util`
  - [x] Deprecate `can-util/js/cid-map` and `can-util/js/cid-set`
  - [x] Update `can-globals`
  - [x] Release
  - [x] Release notes
- [x] `can-view-callbacks`
  - [x] Fix https://github.com/canjs/can-view-callbacks/issues/60
  - [x] Release
  - [x] Release notes
- [x] `can-ajax` release notes
- [x] `can-globals` release notes

**Comment by bmomberger-bitovi** [comment]
A couple of notes.

* cid-set should go where cid-map goes, even though it's not relevant to the current task.
* :+1: to can-dev being its own package, but it depends on can-util/js/log/log, so that would also have to be a can-log package (or combine them into can-log and can-log/dev).

Otherwise it seems consistent (if a good bit of work).

**Comment by imaustink** [comment]
`can-util` must also be removed from `can-vdom` as it is a dev dependency of `can-globals` and it uses `can-util/dom/child-nodes`.
