### ISSUE TITLE
Broken link: is-function

### ISSUE THREAD

**Issue by bgando** [canjs/can-util#386]
https://github.com/canjs/can-util/blob/master/doc/can-util.md

![image](https://user-images.githubusercontent.com/3348231/32755499-76f827c8-c88a-11e7-92ae-32e9220d09d5.png)

**Comment by phillipskevin** [comment]
The URL of the `is-function` docs is wrong, and also the signature looks strange:

![image](https://user-images.githubusercontent.com/5851984/32845741-2249b982-c9eb-11e7-9f68-87fe6790545f.png)

Looking at the docs source, it was not readily apparent why that is.

**Comment by justinbmeyer** [comment]
this is a parsing error with bit-docs .... it sees `function` and does special stuff ... it shouldn't here.

**Comment by imaustink** [comment]
@justinbmeyer where does this happen in `bit-docs`? I am not having any luck tracking it down.

**Comment by phillipskevin** [comment]
@imaustink should we re-publish the site to get this fix? Or do we have to wait for a new canjs  release?

**Comment by imaustink** [comment]
@phillipskevin I am going to republish the site, I had to release this and couple other fixes first but It should be all settled now.

**Comment by imaustink** [comment]
@phillipskevin actually, I need to release `bit-docs` and I don't currently have permission for it so I will release tomorrow.
