### ISSUE TITLE
Make test's work in NodeJS

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-util#4]
We'll probably have to re-write tests in Mocha or Jasmine.

We'll need to import can-simple-dom and make sure all the DOM tests pass.

**Comment by Bajix** [comment]
Check out [karma](https://www.npmjs.com/package/karma)

It automates running Jasmine/Mocha/QUnit and others within real browsers / multiple browsers, and has a [cordova launcher](https://www.npmjs.com/package/karma-cordova-launcher) to run tests on a local mobile device emulator.

It also generates the HTML pages on the fly, which IMO makes things easier.

**Comment by justinbmeyer** [comment]
@Bajix We use testee (it's already implemented).  Does all the same stuff, but I like it more.

This issue isn't to setup a browser launcher (already done), it's to make tests run directly in Node's environment.

**Comment by justinbmeyer** [comment]
Here's what it looks like for testee to do the same things you mentioned Karma does: https://github.com/canjs/can-util/blob/master/package.json#L15

**Comment by matthewp** [comment]
I believe this is happening now, no?  At least the js tests are running.

**Comment by justinbmeyer** [comment]
Yes, but the DOM tests should be made to work against vdom before closing this.
