### ISSUE TITLE
The folder structure is awkward

### ISSUE THREAD

**Issue by Bajix** [canjs/can-util#8]
Thoughts on changing up the folder structure here?

1) A `js` folder is somewhat non-standard. Usually node packages would call this main folder `lib`

```
require('`can-util/lib/cid') vs require('can-util/js/cid')
```

2) Any way we can take advantage of CommonJS naming conventions?

`require('can-util/js/is-browser-window/is-browser-window')` is an absolute mouthful

`require('can-util/is-browser-window')` or `require('can-util/lib/is-browser-window')` are both more palatable

**Comment by justinbmeyer** [comment]
@Bajix like I mentioned in gitter, we're not going to change our use of modlets.  Please work on the CJS folks to adopt this.  They probably won't.  But it's how we organize everything at bitovi.  

The folders are organized that way to separate out pure JavaScript helpers from our DOM helpers.  I think this is a very nice delineation of what's required to use each set of helpers.  I wouldn't want them all mashed up in one `lib` folder.

**Comment by Bajix** [comment]
> @Bajix like I mentioned in gitter, we're not going to change our use of modlets. Please work on the CJS folks to adopt this. They probably won't. But it's how we organize everything at bitovi.

I don't think there's any chance of the CJS community adopting your naming conventions. Specifically, this whole double basename thing isn't going to fly. `require('can/lib/is-browser-window')` > `require('can-util/lib/is-browser-window/is-browser-window')`

You're going against the grain on one of the very, very, few things that are sacred in NodeJS land. Maybe it's irrelevant if `main` is the only thing being directly required. Still, it's a slippery slope that's bound to create friction.

It's perfectly acceptable to agree to disagree on this point.

> The folders are organized that way to separate out pure JavaScript helpers from our DOM helpers. I think this is a very nice delineation of what's required to use each set of helpers. I wouldn't want them all mashed up in one lib folder.

Originally I was going to say maybe renaming `js` -> `lib` and moving `dom` -> `lib/dom` would be reasonable, however now I can't help but wonder if it actually makes more sense to release this as an entirely separately package, say `can-dom`. Substituting  `can-vdom` for `can-dom` for SSR is more reasonable than making can-util require special configuration, and being able to load `can-util` directly in NodeJS is huge. That opens up the possibility of can.Map being used in NodeJS in a standalone fashion, which is quite appealing.

What would you say differentiates a modlet from a package? The two seem largely synonymous, save for the lack of an explicit `package.json`.
