### ISSUE TITLE
$focused should change after previous events

### ISSUE THREAD

**Issue by matthewp** [canjs/can-util#80]
Writing a test for this could be difficult.

**Comment by justinbmeyer** [comment]
I confirmed that 

```
<input class="edit" type="text"
        {$focused}="isEditing(this)"
        {($value)}="name"
        ($enter)="updateName()"
        ($blur)="cancelEdit()"/>
```

doesn't work in todomvc without this.

**Comment by justinbmeyer** [comment]
afterPreviousEvents doesn't work.  Not sure why exactly, but:

```
can.batch.after(this.focus.bind(this));
```

does.  But only if events are batched.

I think I need to change can-event to always batch every event no matter what.

**Comment by matthewp** [comment]
So should it call `types.after` or `types.afterPrevious`?

**Comment by matthewp** [comment]
Went with `types.afterEvents` for now.

**Comment by justinbmeyer** [comment]
AfterEvents won't work.  I'll be free in 10 to talk

**Comment by justinbmeyer** [comment]
Created a test at:

https://github.com/canjs/canjs/tree/todomvc-no-focus

Run it here:

http://localhost:8080/canjs/docs/can-guides/experiment/todomvc/test.html

You'll have to run `node ./build.js` first.  But it shows that dblclicking doesn't add focus.
