### ISSUE TITLE
IE10: get, set, and addEventListener on focused

### ISSUE THREAD

**Issue by daffl** [canjs/can-util#88]
https://github.com/canjs/can-util/blob/master/dom/attr/attr-test.js#L215 is failing on IE10:

![screen shot 2016-09-20 at 4 36 10 pm](https://cloud.githubusercontent.com/assets/338316/18692629/815d172a-7f50-11e6-8619-43fe051659e1.png)

**Comment by matthewp** [comment]
The problem is that focused fires asynchronously in IE10. So going to make the test asynchronous.
