### ISSUE TITLE
IE10: Removing an option causes the select's value to be re-evaluated

### ISSUE THREAD

**Issue by daffl** [canjs/can-util#89]
https://github.com/canjs/can-util/blob/master/dom/attr/attr-test.js#L383 is getting stuck in IE 10:

![screen shot 2016-09-20 at 4 37 49 pm](https://cloud.githubusercontent.com/assets/338316/18692636/a3f39994-7f50-11e6-9992-2bc2651b7f46.png)

**Comment by daffl** [comment]
This seems to also intermittently fail on Firefox (45, Windows)

**Comment by matthewp** [comment]
There's a couple of others that I'm fixing along with this.
