### ISSUE TITLE
can-util/dom/demos/can-util/input-focused Demo is a 404

### ISSUE THREAD

**Issue by Sinjhin** [canjs/can-util#91]
This breaks the demo on http://canjs.github.io/canjs/doc/can-util/dom/attr/attr.special.focused.html

**Comment by phillipskevin** [comment]
This demo is working fine now.

![image](https://cloud.githubusercontent.com/assets/5851984/20317256/e052fc6c-ab2a-11e6-9a0c-8cc59ea82e7b.png)
